### PR TITLE
development of bluegenes wrapper for JBrowse tool

### PR DESCRIPTION
**Pull request by Sakshisrivastava413**
Iframe embedding of jbrowse tool according to the passed gene data.

Facing issue while running test. The project is scaffolded using JS but running test is throwing error: ` Cannot find module '@babel/preset-env'` which is needed mainly in react projects.

### CODE REVIEW

**Comment by Sakshisrivastava413** [comment]
@uosl I pushed the code without running tests as I was unable to figure out the reason of error as mentioned above in the description. Please try running the default test at your end.

**Comment by heralden** [comment]
I get the same error when running tests. :sweat_smile:  I am going to be very lazy now and suggest starting from a clean, newly generated tool scaffold and copying the changes over. Would you like to try this?

**Comment by Sakshisrivastava413** [comment]
Liked your suggestion as I also wasn't able to reproduce the source of error. Please create a new repo. Would like to work on it.

**Review by heralden — APPROVED** [review]
Thanks, seems to work fine now!

Looking at the diff, I'm guessing the `.babelrc` file which was setup for React was causing the problems.

**Pull request merged**
